default:
  before_script: [bun i --frozen-lockfile]
  image: oven/bun
  tags: [saas-linux-small-amd64]
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
stages: [test, secret-detection, e2e, deploy]
workflow:
  name: '$CI_COMMIT_REF_NAME'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(main|develop|release\/.+)$/
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == 'push'
      when: never
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop|release\/.+)$/
sast:
  stage: test
  inherit:
    default: false
variables:
  SECRET_DETECTION_ENABLED: 'true'
secret_detection:
  stage: secret-detection
  inherit:
    default: false