export const CHECKMATE = 'Checkmate'
export const STALEMATE = 'Stalemate'
export const REPETITION = 'Repetition'
export const RESIGNATION = 'Resignation'
export const ABANDONMENT = 'Abandonment'
export const NO_PROGRESS = 'No Progress'
export const INSUFFICIENT_MATERIAL = 'Insufficient Material'
export const AGREEMENT = 'Agreement'
export const PLIES_PER_MOVE = 2
export const REPETITION_LIMIT = 3
export const NO_PROGRESS_BASE = 60
export const NO_PROGRESS_PER_PIECE = 2
export const STARTING_PIECES = 52