name: CI
run-name: CI on ${{ github.ref_name }} by @${{ github.actor }}
on:
  pull_request:
    branches: [main, develop, 'release/**']
  push:
    branches: [main, develop, 'release/**']
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: oven-sh/setup-bun@v2.2.0
      - run: bun i --frozen-lockfile
      - run: bun format:check
      - run: bunx wrangler types --cwd worker/
      - run: bun lint
    timeout-minutes: 5
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: oven-sh/setup-bun@v2.2.0
      - run: bun i --frozen-lockfile
      - run: bun run test
    timeout-minutes: 5
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: oven-sh/setup-bun@v2.2.0
      - run: bun i --frozen-lockfile
      - run: bun run build
    timeout-minutes: 10
  e2e:
    needs: [lint, test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: oven-sh/setup-bun@v2.2.0
      - run: bun i --frozen-lockfile
      - run: bunx playwright install --with-deps
      - run: bun run test:e2e
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      - if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7.0.1
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
    timeout-minutes: 180